/**
 * Mazel patch M8: a Stop hook must never produce a visible double answer.
 *
 * The Stop hook `.claude/scripts/antwort-stil-hook.py` answers with
 * `{"decision":"block","reason":"..."}` when an answer breaks the style contract.
 * The CLI cannot retract the answer it already streamed. Measured on 2026-07-29
 * against the real Agent SDK, the block arrives as:
 *
 *   { type: 'user', isSynthetic: true,
 *     message: { role: 'user', content: 'Stop hook feedback:\n<reason>' } }
 *
 * Before this patch the Claude provider yielded nothing for that message and the
 * rewrite was appended to the SAME bubble: the user read the rejected draft and
 * the corrected version back to back. 85 such pairs were measured across 13
 * sessions, 38 of them over 70 % identical.
 *
 * The patch turns the feedback into a `stop_hook_retry` chunk and discards the
 * draft text (never the tool calls, they really ran).
 */
import { createMockEl } from '@test/helpers/mockElement';

import type { ChatMessage, StreamChunk } from '@/core/types';
import { StreamController } from '@/features/chat/controllers/StreamController';
import { ChatState } from '@/features/chat/state/ChatState';
import {
  extractStopHookFeedback,
  STIL_BLOCK_MARKER,
  STOP_HOOK_FEEDBACK_PREFIX,
} from '@/providers/claude/sdk/stopHookFeedback';
import { transformSDKMessage } from '@/providers/claude/stream/transformClaudeMessage';

// ---------------------------------------------------------------- detection

function syntheticFeedback(reason: string): { type: string } & Record<string, unknown> {
  return {
    type: 'user',
    isSynthetic: true,
    parent_tool_use_id: null,
    message: { role: 'user', content: `${STOP_HOOK_FEEDBACK_PREFIX}\n${reason}` },
  };
}

describe('mazel patch M8: stop-hook feedback is recognized', () => {
  it('reads the reason out of the synthetic user message', () => {
    expect(extractStopHookFeedback(syntheticFeedback('Ein Absatz hat 4 Saetze.')))
      .toBe('Ein Absatz hat 4 Saetze.');
  });

  it('accepts the block-array form of the same message', () => {
    const message = {
      type: 'user',
      isSynthetic: true,
      message: {
        role: 'user',
        content: [{ type: 'text', text: `${STOP_HOOK_FEEDBACK_PREFIX}\nGeviertstrich gefunden.` }],
      },
    };
    expect(extractStopHookFeedback(message)).toBe('Geviertstrich gefunden.');
  });

  it('ignores a HUMAN message that merely quotes the prefix', () => {
    // Counter-check: without this, Gabriel asking about the hook would erase an answer.
    const message = {
      type: 'user',
      message: { role: 'user', content: `${STOP_HOOK_FEEDBACK_PREFIX} was bedeutet das?` },
    };
    expect(extractStopHookFeedback(message)).toBeNull();
  });

  it('ignores synthetic messages that are not stop-hook feedback', () => {
    const message = {
      type: 'user',
      isSynthetic: true,
      message: { role: 'user', content: 'Caveat: the messages below were generated by the user.' },
    };
    expect(extractStopHookFeedback(message)).toBeNull();
  });

  it('ignores assistant messages', () => {
    expect(extractStopHookFeedback({ type: 'assistant' })).toBeNull();
  });

  it('detects the block even WITHOUT isSynthetic, when our own marker is there', () => {
    // `isSynthetic` belongs to the SDK. The CLI's persisted transcript already
    // stores the same message as `isMeta: true` without the flag (measured
    // 2026-07-29, CLI 2.1.220). If the stream ever follows, detection must hold.
    const message = {
      type: 'user',
      isMeta: true,
      message: {
        role: 'user',
        content: `${STOP_HOOK_FEEDBACK_PREFIX}\n${STIL_BLOCK_MARKER} Ein Absatz hat 4 Saetze.`,
      },
    };
    expect(extractStopHookFeedback(message)).toBe(`${STIL_BLOCK_MARKER} Ein Absatz hat 4 Saetze.`);
  });

  it('still ignores a human message quoting the prefix without the marker', () => {
    // Negative control for the route above: the fallback needs OUR marker, so a
    // question about the hook cannot erase an answer.
    const message = {
      type: 'user',
      message: { role: 'user', content: `${STOP_HOOK_FEEDBACK_PREFIX}\nwas bedeutet das?` },
    };
    expect(extractStopHookFeedback(message)).toBeNull();
  });

  it('still detects the block when the CLI renames its own prefix', () => {
    // Belt and braces: `Stop hook feedback:` belongs to the CLI. Our hook owns
    // `[STIL-BLOCK]`, so a silent upstream rename cannot bring the double back.
    const message = {
      type: 'user',
      isSynthetic: true,
      message: { role: 'user', content: `Hook output:\n${STIL_BLOCK_MARKER} Ein Absatz hat 4 Saetze.` },
    };
    expect(extractStopHookFeedback(message)).toBe('Ein Absatz hat 4 Saetze.');
  });
});

describe('mazel patch M8: transform emits a retry chunk', () => {
  it('yields stop_hook_retry instead of nothing', () => {
    const events = [...transformSDKMessage(syntheticFeedback('Zu viel Fliesstext.') as never)];
    expect(events).toEqual([{ type: 'stop_hook_retry', reason: 'Zu viel Fliesstext.' }]);
  });

  it('does not swallow a real tool result', () => {
    const message = {
      type: 'user',
      parent_tool_use_id: null,
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 'tool-1', content: 'ok', is_error: false }],
      },
    };
    const events = [...transformSDKMessage(message as never)];
    expect(events.some(event => event.type === 'tool_result')).toBe(true);
  });
});

// ------------------------------------------------------------- draft discard

function createController(): { controller: StreamController; state: ChatState } {
  const state = new ChatState();
  state.currentContentEl = createMockEl() as never;
  const controller = new StreamController({
    plugin: { settings: { permissionMode: 'yolo' }, app: { vault: { adapter: { basePath: '/v' } } } },
    state,
    renderer: { renderContent: jest.fn(), addTextCopyButton: jest.fn() },
    subagentManager: { resetStreamingState: jest.fn() },
    getMessagesEl: () => createMockEl() as never,
    getFileContextManager: () => ({ markFileBeingEdited: jest.fn(), trackEditedFile: jest.fn() }),
    updateQueueIndicator: jest.fn(),
    getAgentService: () => ({ getSessionId: () => 's1' }),
  } as never);
  return { controller, state };
}

function createMessage(): ChatMessage {
  return {
    id: 'assistant-1',
    role: 'assistant',
    content: '',
    timestamp: 0,
    toolCalls: [],
    contentBlocks: [],
  };
}

const RETRY: StreamChunk = { type: 'stop_hook_retry', reason: 'Ein Absatz hat 4 Saetze.' };

describe('mazel patch M8: the rejected draft is thrown away', () => {
  it('removes the streamed draft from the message content', async () => {
    const { controller, state } = createController();
    const msg = createMessage();

    await controller.handleStreamChunk({ type: 'text', content: 'ERSTE FASSUNG' }, msg);
    expect(msg.content).toBe('ERSTE FASSUNG');

    await controller.handleStreamChunk(RETRY, msg);
    expect(msg.content).toBe('');
    expect(state.currentTextEl).toBeNull();
    expect(state.currentTextContent).toBe('');

    await controller.handleStreamChunk({ type: 'text', content: 'ZWEITE FASSUNG' }, msg);
    await controller.finalizeCurrentTextBlock(msg);

    // The whole point: exactly one version survives.
    expect(msg.content).toBe('ZWEITE FASSUNG');
    expect(msg.contentBlocks).toEqual([{ type: 'text', content: 'ZWEITE FASSUNG' }]);
  });

  it('removes the draft DOM block, so nothing stays on screen', async () => {
    const { controller, state } = createController();
    const msg = createMessage();

    await controller.handleStreamChunk({ type: 'text', content: 'ERSTE FASSUNG' }, msg);
    const draftEl = state.currentTextEl as unknown as { remove: jest.Mock };
    expect(draftEl).not.toBeNull();
    draftEl.remove = jest.fn();

    await controller.handleStreamChunk(RETRY, msg);
    expect(draftEl.remove).toHaveBeenCalledTimes(1);
  });

  it('also discards a draft that was already finalized into contentBlocks', async () => {
    const { controller, state } = createController();
    const msg = createMessage();

    await controller.handleStreamChunk({ type: 'text', content: 'ERSTE FASSUNG' }, msg);
    await controller.finalizeCurrentTextBlock(msg);
    expect(msg.contentBlocks).toHaveLength(1);
    expect(state.currentTextEl).toBeNull();

    await controller.handleStreamChunk(RETRY, msg);
    expect(msg.contentBlocks).toHaveLength(0);
    expect(msg.content).toBe('');
  });

  it('keeps tool calls: they really ran and must not be rewritten away', async () => {
    const { controller, state } = createController();
    const msg = createMessage();

    msg.toolCalls = [{ id: 'tool-1', name: 'Read', input: {}, status: 'complete' } as never];
    msg.contentBlocks = [{ type: 'tool_use', toolId: 'tool-1' }];
    await controller.handleStreamChunk({ type: 'text', content: 'ERSTE FASSUNG' }, msg);

    await controller.handleStreamChunk(RETRY, msg);

    expect(msg.toolCalls).toHaveLength(1);
    expect(msg.contentBlocks).toEqual([{ type: 'tool_use', toolId: 'tool-1' }]);
    expect(msg.content).toBe('');
    expect(state.currentTextContent).toBe('');
  });

  it('end to end: the RECORDED SDK payload leaves exactly one version', async () => {
    // Verbatim capture from a live Agent SDK run against a blocking Stop hook
    // (/tmp/stophook-probe, 2026-07-29). Not hand-written: this is the shape that
    // actually arrives, including `content` as a block array and `isSynthetic`.
    const recorded = {
      type: 'user',
      message: {
        role: 'user',
        content: [{ type: 'text', text: 'Stop hook feedback:\nPROBE: schreibe die Antwort neu und sage nur ZWEITE.' }],
      },
      parent_tool_use_id: null,
      session_id: '65a4dd6e-feab-4646-b58b-7d8136907eaa',
      uuid: '02d8364e-e3ed-4016-9b99-eabda4f069fc',
      timestamp: '2026-07-28T22:44:22.416Z',
      isSynthetic: true,
    };

    const { controller } = createController();
    const msg = createMessage();

    await controller.handleStreamChunk({ type: 'text', content: 'ERSTE' }, msg);
    for (const event of transformSDKMessage(recorded as never)) {
      await controller.handleStreamChunk(event as StreamChunk, msg);
    }
    await controller.handleStreamChunk({ type: 'text', content: 'ZWEITE' }, msg);
    await controller.finalizeCurrentTextBlock(msg);

    expect(msg.content).toBe('ZWEITE');
    expect(msg.content).not.toContain('ERSTE');
  });

  it('is a no-op when the hook blocks before any text was streamed', async () => {
    const { controller } = createController();
    const msg = createMessage();

    await controller.handleStreamChunk(RETRY, msg);

    expect(msg.content).toBe('');
    expect(msg.contentBlocks).toEqual([]);
  });
});
